builds:
  - binary: hello-cli
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
release:
  github:
      owner: avinashupadhya99
      name: hello-cli
  prerelease: auto
universal_binaries:
  - replace: true
